name: CI
on:
  push:
    branches:
      - develop
      - next-minor
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '3.1'
        db:
          - mysql
          - postgresql
        kind:
          - cucumber
          - other
    env:
      DB: ${{ matrix.db }}
      RAILS_ENV: test
      BUNDLE_WITH: ${{ matrix.db }}
      BUNDLE_WITHOUT: development
      BUNDLE_FROZEN: true
      BUNDLE_DISABLE_SHARED_GEMS: true
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y build-essential curl git gsfonts imagemagick libcurl4-openssl-dev libidn11-dev libmagickwand-dev libssl-dev libxml2-dev libxslt1-dev yarnpkg libjs-angularjs npm coreutils
      - name: Start MySQL
        run: sudo systemctl start mysql.service
        if: matrix.db == 'mysql'
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: bundle install
        run: |
          if test -x "$(which bundle)"; then \
            bundle config set --local with 'development'; \
            if test ${{ matrix.db }} == 'mysql'; then \
              bundle config set --local with 'development mysql'; \
            elif test ${{ matrix.db }} == 'postgresql'; then \
              bundle config set --local with 'development postgresql'; \
            fi; \
            bundle install; \
          else \
            echo "missing bundler!"; \
          fi
      - name: Prepare
        run: script/ci/prepare.sh
      - name: Run tests
        run: bin/rake --verbose --backtrace --job-stats --rules --trace ci:${{ matrix.kind }} || ruby -c Rakefile
      - name: Run Jasmine (or lints)
        run: (timeout 3m bin/rake --trace jasmine:ci) || bin/haml-lint || bin/scss-lint
        if: matrix.kind == 'other'
